### PR TITLE
Fix for when you pass a non-object

### PR DESCRIPTION
**Pull request by wesleytodd**
Passing a boolean, string or number causes a hard error.  This make sure that you can pass these non-error types and get the correct behavior.

### CODE REVIEW

**Comment by Raynos** [comment]
Also check for `null` :) `typeof null === 'object'`

**Comment by wesleytodd** [comment]
Technically the problem only happens when you pass a truthy value because of the while loop.  So `null` is already handled in that case.  I added the `false` test just for completeness.  I can add it anyway if you want, just let me know.

**Comment by Raynos** [comment]
Published v2.2.0

**Comment by wesleytodd** [comment]
Awesome! Thanks for the quick turn around.

**Pull request merged**
